name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint Action Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint shell scripts
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './'

      - name: Lint action.yml
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-check
