name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint Action Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint shell scripts
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './'

      - name: Lint action.yml
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-check
  
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bats
        uses: bats-core/bats-action@2.0.0
        with:
          bats-version: 1.10.0

      - name: Setup Bats helper libraries
        run: |
          git clone https://github.com/bats-core/bats-support.git tests/bats-support
          git clone https://github.com/bats-core/bats-assert.git tests/bats-assert

      - name: Run tests
        run: bats tests
